#!/bin/bash

# function to prompt the user for a filename
get_filename() {
	read -p "Filename: " filename
	echo "$filename"
}

# function to create and open a file in the specified directory
open_file() {

	# Cd into the directory
	cd "$1" || exit
	# Create the file in the specified directory
	touch "$1/$filename.md"

	# create unique identifier and links section
	timestamp="$(date +"%Y-%m-%d %H:%M:%S")"

	# format the file
	{
		echo "# $filename"
		echo -en "\n"
		echo -en "\n"
		echo -en "\n"
		echo -en "\n"
		echo "Links:"
		echo -en "\n"
		echo "$timestamp"
	} >>"$1/$filename.md"

	# Open the file in Neovim
	nvim '+ normal ggzzi' "$1/$filename.md" -c 3j
}

# Prompt the user if no filename is provided
if [[ $# -lt 1 ]]; then
	filename=$(get_filename)
fi

# if more than one argument is given, print error message and stop script
if [[ $# -gt 1 ]]; then
	echo "Please provide only one filename separated by dashes, without .md extension."
	echo "Example: note my-new-note"
	exit 1
fi

# set filename to the argument given to the script
if [[ $# -eq 1 ]]; then
	filename=$1
fi

# check if filename is empty
if [[ ! $filename ]]; then
	echo "input a filename!"
	filename=$(get_filename)
fi

# check if file exists
if [[ -f "$HOME/notes/000-inbox/$filename.md" ]]; then
	echo "File already exists!"
	exit 1
fi

open_file "$HOME/notes/000-inbox"
